Add profile for bacula-dir
simondeziel/aa-profiles pull request #8
Opened 2020-05-18 12:52 UTC by BoresXP

2020-05-19 16:11 UTC, simondeziel requested changes
Thanks for the pull request! I just have a few questions before merging it in.

2020-05-21 13:18 UTC, simondeziel requested changes
If you can test the proposed fixes in the example socket paths, that'd be great! Thanks.

2020-05-21 13:18 UTC, simondeziel commented on 20.04/local/usr.sbin.bacula-dir
> +#/var/spool/postfix/pgsql/.s.PGSQL.5432 rw,
I believe you meant `/run/postgresql/.s.PGSQL.5432`

2020-05-21 13:18 UTC, simondeziel commented on 20.04/local/usr.sbin.bacula-dir
> +#/var/run/mysqld/mysqld.sock rw,
Most distros have stopped using `/var/run` and since moved to `/run` only. If you want to support both the common idiom is to use `/{,var/}run/`.

2020-05-21 13:34 UTC, BoresXP commented on 20.04/local/usr.sbin.bacula-dir
> +#/var/spool/postfix/pgsql/.s.PGSQL.5432 rw,
Right, that's location is correct only for me.

2020-05-21 20:45 UTC, simondeziel approved these changes

2020-05-21 20:45 UTC, simondeziel approved these changes

2020-05-21 20:46 UTC, merged